#!/bin/bash

if [ $# -lt 1 ]; then
	echo "Skladnia: $0 [nazwa uzytkownika]"
	exit 1
else
	USERR=$1
fi

trap "exit 0" 2 3

while [ 1 ]; do
	ANS=`ps axo user,rss | awk 'BEGIN {sum=0} {if ($1=='\"$USERR\"') sum=sum+$2} END {print sum}'`
	echo $ANS
	sleep 2
done
