#!/bin/bash

if [ $# -lt 1 ]; then
	PTH=`pwd`
else
	PTH=$1
fi

if [ ! -d $PTH ]; then
	echo "$PTH: nie katalog"
	exit 1
fi

SUM=0
AMNT=0

for FILE in $PTH/*; do
	if [ -f $FILE -a ! -h $FILE ]; then
		SIZE=`wc -c $FILE | awk '{print $1}'`
		SUM=`expr $SUM + $SIZE`
		AMNT=`expr $AMNT + 1`
	fi
done

ANS=`expr $SUM / $AMNT`
echo $ANS
