#!/bin/bash

USERSLOGGEDIN=`who | awk '{print $1}' | sort | uniq`

USERSOWNERSOFPROCESSES=`ps axo user | tail -n+2 | sort | uniq`

for USROWNROFPRCSS in $USERSOWNERSOFPROCESSES; do
	FLAG=1
	for USRLGGDIN in $USERSLOGGEDIN; do
		if [ "$USROWNROFPRCSS" = "$USRLGGDIN" ]; then
			FLAG=0
		fi
	done
	if [ $FLAG -eq 1 ]; then
		echo $USRLGGDIN
	fi
done
