#!/bin/bash

trap 'date; exit 0' 2 3

if [ $# -eq 0 ]; then
	echo -n "Podaj numery użytkowników: "
	read UIDS
else
	UIDS=$*
fi

while [ 1 ]; do
	echo ""
	echo "NUMER	NAZWA	CZAS [s]"
	DATA=`ps axo uid,time | tail -n+2 | awk '{print $1":"$2}'`
	for UIDE in $UIDS; do
		SUM=`echo "$DATA" | grep "^$UIDE:"| awk -F: 'BEGIN {sum=0} {sum=sum+$2*3600+$3*60+$4} END {print sum}'`
		UNAME=`cat /etc/passwd | awk -F: '{if ($3 == "'$UIDE'") print $1}'`
		echo "$UIDE	$UNAME	$SUM"
	done
	sleep 2
done
