#!/bin/bash

if [ $# -lt 1 ]; then
	echo -n "Podaj userow, ktorych chcesz sprawdzac: "
	read USRLIST
else
	USRLIST=$*
fi

for USR in $USRLIST; do
	SUM=`ps axo user,rss | tail -n+2 | awk 'BEGIN {sum=0} {if ( $1 == "'$USR'" ) sum=sum+$2} END {print sum}'`
	echo "$USR $SUM"
done
