#!/bin/bash

if [ $# -lt 1 ]; then
	echo -n "Czas w sekundach: "
	read ARGS
	FLAG=0
	for TM in $ARGS; do
		if [ $FLAG -eq 0 ]; then
			FLAG=1
			MINTIME=$TM
		fi
	done	
else
	MINTIME=$1
fi

PSTIMES=`ps axo time | tail -n+2 | awk -F: '{print $1*3600+$2*60+$3}'`
ANS=0

for PSTIM in $PSTIMES; do
	if [ $PSTIM -gt $MINTIME ]; then
		ANS=`expr $ANS + 1`
	fi
done

echo $ANS
