#!/bin/bash

trap "echo 'Konczenie...'; exit 0" 2 3

if [ $# -lt 1 ]; then
	echo -n "Nazwa uzytkownika: "
	read USR
else
	USR=$1
fi

while [ 0 ]; do
	USRLIST=`who | awk '{print $1}' | sort | uniq`
	for USRLOGGEDIN in $USRLIST; do
		if [ $USR == $USRLOGGEDIN ]; then
			echo "Uzytkownik zalogowany."
			exit 0
		fi
	done
	sleep 5
done
