#!/bin/bash

if [ "$1" == "docs" ]; then
    cd docs; doxygen; exit 0
elif [ "$1" == "docs-pdf" ]; then
    cd docs; doxygen; cd latex; make; cp refman.pdf ../DOKUMENTACJA_TECHNICZNA.pdf; exit 0
fi

python3 src/triangulate.py
